name: Test
run-name: Test
on:
  workflow_call:
    inputs:
      code-quality-may-fail:
        type: boolean
        default: false
        description: Determines if the workflow should continue when the Code Quality check fails
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: pip install poetry
      - name: Install main and dev requirements
        run: poetry install --with dev
      - name: Run unit tests
        run: pytest
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.code-quality-may-fail }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install main and dev requirements
        run: poetry install --with dev
      - name: PyCodeStyle (source code)
        run: pycodestyle --show-pep8 src/
      - name: PyLint (source code)
        run: pylint src/
      - name: Flake8 (source code)
        run: flake8 src/
      - name: PyDocStyle (source code)
        run: pydocstyle src/
      - name: MyPy (source code)
        run: mypy src/
