name: Publish docs
run-name: Publish docs
on:
  workflow_call:
    
jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pip3 install poetry
      - name: Install dependencies
        shell: bash
        run: poetry install --with doc
      - name: Sphinx build
        run: poetry run sphinx-build docs/source docs/build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: 'docs/build/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2