name: Test and deploy (dev)
run-name: Test and deploy (dev)
on:
  push:
    # branches:
    #   main

jobs:
  integration:
    name: Integration testing
    uses: ./.github/workflows/_integration.yml
  build-and-deploy:
    name: Deployment
    uses: ./.github/workflows/_deploy.yml
    needs: integration
    secrets:
      repository_directory: ${{ secrets.CB_KR23_REPO_DIR }}
