name: Test and deploy
run-name: Test the code and deploy the library
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install app requirements
        run: pip install -r src/requirements.txt
      - name: Run unit tests
        uses: paolorechia/fast-pytest-github-action@develop
        with:
          pytest_args: "tests"
          requirements_file: "src/requirements-tests.txt"
