name: Unit tests
run-name: Execute unit tests
on: [push]
jobs:
  unit-test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install app requirements
        run: pip install -r src/requirements.txt
      - name: Install test requirements
        run: pip install -r src/requirements-tests.txt
      - name: Run unit tests
        run: pytest
  code-quality:
    name: Checking code quality
    runs-on: ubuntu-latest
    steps:
      - name: Install app requirements
        run: pip install -r pylint
      - name: PyLint
        run: pylint --errors-only src/
